version: "3.4"

services:

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=animal
      - POSTGRES_USER=maria
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: "exit 0"

  api:
    image: node:latest
    volumes:
      - ./api/bin:/app
    command: /bin/sh -c "cd /app && npm install && node /app/server.js"
    links:
      - "db:db"
    ports:
      - 81:8000
      - 443:443